#!/bin/bash

# Update package lists
sudo apt update

# Install Java OpenJDK
sudo apt install openjdk-11-jdk -y

# Add Jenkins repository key
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -

# Add Jenkins repository
sudo echo "deb https://pkg.jenkins.io/debian-stable binary/" >> /etc/apt/sources.list

# Update package lists again
sudo apt update

# Install Jenkins
sudo apt install jenkins -y

# Enable and start Jenkins service
sudo systemctl enable jenkins
sudo systemctl start jenkins

# Print success message
echo "Jenkins installation complete! Access Jenkins at http://localhost:8080"
echo "**Important:** The initial password to unlock Jenkins is located at /var/lib/jenkins/secrets/initialAdminPassword"
